development:
  adapter: postgresql
  encoding: unicode
  database: taxes3_db_dev
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: taxes3_db_test
  pool: 5
  username: postgres
  password: root
